---
- name: load fileserver
  hosts: utility
  become: true
  collections:
     - community.sap_launchpad

  ### This playbook downloads all the SAP files required for installing
  ### SAP HANA and S/4 HANA from Maintenance Planner
  vars_prompt:
    - name: "suser_id"
      prompt: "S-User ID"
      private: false
      default: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_USERNAME')}}"
    - name: "suser_password"
      prompt: "S-User PW"
      private: true
      default: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_PASSWORD')}}"

  vars:
      sap_swpm_software_path: /sap-software

  vars_files: sap-dl.yml

  tasks:
    - name: ensure S-USER and PASSWORD are defined
      fail:
            msg: "Please set SAP_SUPPORT_DOWNLOAD_USERNAME and SAP_SUPPORT_DOWNLOAD_PASSWORD"
      when: ( suser_id|trim ==''  )  or  ( suser_password|trim == '' )
      tags:
        - sap_s4_softwaredownload
        - sap_extra_download

    - name: ensure prereqs are installed
      pip:
        name:
          - urllib3
          - beautifulsoup4
          - lxml
          - requests
        state: present
        virtualenv: "{{ venv | default(omit) }}"

    - name: Ensure download directories exist
      file:
         path: "{{ item }}"
         state: directory
         mode: '0755'
      loop:
        - "{{ sap_swpm_software_path }}"
        - "{{ sap_swpm_software_path }}/HANA2SPS06"
        - "{{ sap_swpm_software_path }}/S4HANA2021.FNDN"

    - name: download SAPCAR
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ sap_swpm_software_path }}"
        dry_run: "{{ dryrun|default(false) }}"
      loop: "{{ sapcar }}"
      ignore_errors: true

    - name: download Hana Media
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ sap_swpm_software_path }}/HANA2SPS06"
        dry_run: "{{ dryrun|default(false) }}"
      loop: "{{ hdb2sps06 }}"
      ignore_errors: true

    - name: download S4 Media
      community.sap_launchpad.software_center_download:
        suser_id: "{{ suser_id }}"
        suser_password: "{{ suser_password }}"
        softwarecenter_search_query: "{{ item }}"
        dest: "{{ sap_swpm_software_path }}/S4HANA2022.FNDN"
        dedup: "last"
        dry_run: "{{ dryrun|default(false) }}"
      loop: "{{ s4fndn2021 + swpm }}"
      ignore_errors: true

    - name: Link SAPCAR
      ansible.builtin.file:
        src: '{{ sap_swpm_software_path }}/{{ sapcar | first }}'
        dest: '{{ item }}'
        state: hard
      loop:
        - '{{ sap_swpm_software_path }}/S4HANA2022.FNDN/{{ sapcar | first }}'
        - '{{ sap_swpm_software_path }}/HANA2SPS06/{{ sapcar | first }}'
    
   
